name: "Podcast Generator"
author: "Thomas Purk"
description: "Generates a feed for a poscast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actor }}